# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
inhibit_all_warnings!

target 'SkurtChallenge' do
    pod "AFNetworking"
    pod 'MagicalRecord'
    pod 'PureLayout'
#    pod 'FormatterKit'

end

target 'SkurtChallengeTests' do

end

target 'SkurtChallengeUITests' do

end

